name: TWRP CI

on:
  workflow_dispatch:

jobs:
  build:
    name: TWRP Build CI
    runs-on: ubuntu-18.04

    env:
      OEM: samsung
      DEVICE: j1pop3g
      BRANCH: twrp-5.1

    steps:
      - uses: actions/checkout@v2

      - name: Installing JDK 7 + Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zip gcc-multilib g++-multilib \
            libc6-dev-i386 lib32ncurses5-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc schedtool axel
          mkdir ~/.jdk_7
          cd ~/.jdk_7
          axel -q -n $(nproc --all) https://download.java.net/openjdk/jdk7u75/ri/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
          tar -xzf openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
          sudo ln -f -s /usr/bin/python2.7 /usr/bin/python

      - name: Syncing TWRP sources
        run: |
          mkdir ~/TWRP
          cd ~/TWRP

          mkdir ~/.bin
          curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          python3 ~/.bin/repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b ${{ env.BRANCH }}
          python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          git clone --branch ${{ env.BRANCH }} --single-branch https://github.com/J110H-Android/twrp_device_${{ env.OEM }}_${{ env.DEVICE }}.git ~/TWRP/device/${{ env.OEM }}/${{ env.DEVICE }}

      - name: Building TWRP
        run: |
          OLDPATH=$PATH
          OLDJAVAHOME=$JAVA_HOME
          export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
          export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
          cd ~/TWRP
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export LC_ALL=C
          lunch omni_${{ env.DEVICE }}-eng
          make -j$(nproc --all) recoveryimage
          export PATH=$OLDPATH
          export JAVA_HOME=$OLDJAVAHOME

      - name: Uploading TWRP builds
        uses: actions/upload-artifact@v2
        with:
          name: twrp
          path: /home/runner/TWRP/out/target/product/${{ env.DEVICE }}/recovery.*
